// lib/features/subscription/presentation/upgrade_screen.dart
//
// Full paywall screen. Reached from:
//   - UpgradeBottomSheet CTA ("Upgrade to Pro")
//   - Settings → Plan & Billing
//
// Route: /upgrade (optionally with extra: {'triggerFeature': 'callRecording'})
//
// On "Subscribe" tap, opens the Stripe/Paddle checkout URL in the browser.
// After payment, the Stripe/Paddle webhook hits your backend Cloud Function,
// which writes to Firestore. The app re-bootstraps on next launch or background
// resume. For an immediate in-session reflect, the user can pull-to-refresh
// on this screen (calls entitlementProvider.notifier.refresh()).

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../../core/theme/app_colors.dart';
import '../../../core/theme/app_spacing.dart';
import '../../../core/entitlements/app_feature.dart';
import '../../../core/entitlements/entitlement_provider.dart';
import '../../../core/entitlements/plan_tier.dart';
import '../../../core/logging/logger_service.dart';
import '../../../features/auth/presentation/providers/auth_session_provider.dart';

// ── Checkout URL constants (replace with your actual Stripe/Paddle links) ─────
// These are the hosted payment page URLs generated by Stripe/Paddle.
// Append ?client_reference_id={institutionId} to associate the payment.
// IMPORTANT: store these in remote config or environment, not hard-coded here.
class _CheckoutUrls {
  static const pro = 'https://buy.stripe.com/YOUR_PRO_LINK';
  static const enterprise = 'https://buy.stripe.com/YOUR_ENTERPRISE_LINK';
  // Paddle alternative: 'https://YOUR_VENDOR.paddle.com/checkout/product/XXX'
}

// ─────────────────────────────────────────────────────────────────────────────

class UpgradeScreen extends ConsumerStatefulWidget {
  /// [triggerFeature] is the feature that prompted this screen (from route extra).
  const UpgradeScreen({super.key, this.triggerFeature});
  final AppFeature? triggerFeature;

  @override
  ConsumerState<UpgradeScreen> createState() => _UpgradeScreenState();
}

class _UpgradeScreenState extends ConsumerState<UpgradeScreen> {
  bool _isRefreshing = false;

  // ── Pull-to-refresh: re-check entitlements after user returns from browser ──
  Future<void> _refresh() async {
    setState(() => _isRefreshing = true);
    try {
      final session = ref.read(authSessionProvider);
      if (session?.institutionId != null) {
        await ref
            .read(entitlementProvider.notifier)
            .refresh(institutionId: session!.institutionId!);
      }
    } catch (e) {
      LoggerService.instance.log(
        LogLevel.warning,
        'UpgradeScreen',
        'Refresh failed: $e',
      );
    } finally {
      if (mounted) setState(() => _isRefreshing = false);
    }
  }

  Future<void> _launchCheckout(PlanTier tier, String institutionId) async {
    final baseUrl =
        tier == PlanTier.pro ? _CheckoutUrls.pro : _CheckoutUrls.enterprise;

    // Append institution ID so webhook can find the right Firestore document.
    final url = Uri.parse('$baseUrl?client_reference_id=$institutionId');

    LoggerService.instance.log(
      LogLevel.info,
      'UpgradeScreen',
      'Launching checkout for ${tier.displayName}',
    );

    if (await canLaunchUrl(url)) {
      await launchUrl(url, mode: LaunchMode.externalApplication);
    } else {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Could not open checkout page.')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final currentTier = ref.watch(currentTierProvider);
    final institutionId = ref.read(authSessionProvider)?.institutionId ?? '';

    return Scaffold(
      backgroundColor: AppColors.surface,
      appBar: AppBar(
        title: const Text('Choose Your Plan'),
        centerTitle: true,
        actions: [
          if (_isRefreshing)
            const Padding(
              padding: EdgeInsets.all(16),
              child: SizedBox(
                  width: 20,
                  height: 20,
                  child: CircularProgressIndicator(strokeWidth: 2)),
            )
          else
            IconButton(
              icon: const Icon(Icons.refresh),
              tooltip: 'Already paid? Refresh',
              onPressed: _refresh,
            ),
        ],
      ),
      body: RefreshIndicator(
        onRefresh: _refresh,
        child: ListView(
          padding: const EdgeInsets.all(AppSpacing.screenPadding),
          children: [
            if (widget.triggerFeature != null) ...[
              _FeatureHighlightBanner(feature: widget.triggerFeature!),
              const SizedBox(height: AppSpacing.xl),
            ],
            _PlanCard(
              tier: PlanTier.pro,
              isCurrent: currentTier == PlanTier.pro,
              isHighlighted: true,
              triggerFeature: widget.triggerFeature,
              onSubscribe: () => _launchCheckout(PlanTier.pro, institutionId),
            ),
            const SizedBox(height: AppSpacing.lg),
            _PlanCard(
              tier: PlanTier.enterprise,
              isCurrent: currentTier == PlanTier.enterprise,
              triggerFeature: widget.triggerFeature,
              onSubscribe: () =>
                  _launchCheckout(PlanTier.enterprise, institutionId),
            ),
            const SizedBox(height: AppSpacing.xxl),
            _FeatureComparisonTable(currentTier: currentTier),
            const SizedBox(height: AppSpacing.xl),
            Text(
              'Subscriptions renew automatically. Cancel anytime from your '
              'billing portal. All prices exclude applicable taxes.',
              textAlign: TextAlign.center,
              style: TextStyle(
                fontSize: 12,
                color: AppColors.secondary.withValues(alpha: 0.7),
                height: 1.5,
              ),
            ),
            const SizedBox(height: AppSpacing.xxl),
          ],
        ),
      ),
    );
  }
}

class _FeatureHighlightBanner extends StatelessWidget {
  const _FeatureHighlightBanner({required this.feature});
  final AppFeature feature;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(AppSpacing.md),
      decoration: BoxDecoration(
        color: AppColors.primary.withValues(alpha: 0.08),
        borderRadius: BorderRadius.circular(AppSpacing.radiusMd),
        border: Border.all(color: AppColors.primary.withValues(alpha: 0.3)),
      ),
      child: Row(
        children: [
          Icon(Icons.lock_open_rounded, color: AppColors.primary, size: 20),
          const SizedBox(width: AppSpacing.sm),
          Expanded(
            child: Text(
              'Unlock ${feature.displayName}',
              style: TextStyle(
                  color: AppColors.primary, fontWeight: FontWeight.w600),
            ),
          ),
        ],
      ),
    );
  }
}

class _PlanCard extends StatelessWidget {
  const _PlanCard({
    required this.tier,
    required this.isCurrent,
    required this.onSubscribe,
    this.isHighlighted = false,
    this.triggerFeature,
  });

  final PlanTier tier;
  final bool isCurrent;
  final bool isHighlighted;
  final AppFeature? triggerFeature;
  final VoidCallback onSubscribe;

  String get _priceLabel {
    switch (tier) {
      case PlanTier.pro:
        return '\$29 / month';
      case PlanTier.enterprise:
        return '\$99 / month';
      default:
        return 'Free';
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: AppColors.surface,
        borderRadius: BorderRadius.circular(AppSpacing.radiusLg),
        border: Border.all(
          color: isHighlighted
              ? AppColors.primary
              : AppColors.secondary.withValues(alpha: 0.2),
          width: isHighlighted ? 2 : 1,
        ),
        boxShadow: isHighlighted
            ? [
                BoxShadow(
                  color: AppColors.primary.withValues(alpha: 0.12),
                  blurRadius: 16,
                  offset: const Offset(0, 4),
                )
              ]
            : null,
      ),
      child: Padding(
        padding: const EdgeInsets.all(AppSpacing.lg),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Text(tier.displayName,
                    style: const TextStyle(
                        fontSize: 20, fontWeight: FontWeight.w700)),
                if (isHighlighted) ...[
                  const SizedBox(width: AppSpacing.sm),
                  Container(
                    padding:
                        const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                    decoration: BoxDecoration(
                      color: AppColors.primary,
                      borderRadius: BorderRadius.circular(999),
                    ),
                    child: const Text('Popular',
                        style: TextStyle(
                            color: Colors.white,
                            fontSize: 11,
                            fontWeight: FontWeight.w700)),
                  ),
                ],
                const Spacer(),
                Text(_priceLabel,
                    style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.w600,
                        color: AppColors.primary)),
              ],
            ),
            const SizedBox(height: AppSpacing.md),
            ...tier.allowedFeatures
                .where((f) => !PlanTier.free.includes(f))
                .map((f) => _FeatureRow(
                      feature: f,
                      isHighlighted: f == triggerFeature,
                    )),
            const SizedBox(height: AppSpacing.lg),
            SizedBox(
              width: double.infinity,
              child: isCurrent
                  ? OutlinedButton(
                      onPressed: null, child: const Text('Current Plan'))
                  : FilledButton(
                      onPressed: onSubscribe,
                      child: Text('Subscribe to ${tier.displayName}'),
                    ),
            ),
          ],
        ),
      ),
    );
  }
}

class _FeatureRow extends StatelessWidget {
  const _FeatureRow({required this.feature, this.isHighlighted = false});
  final AppFeature feature;
  final bool isHighlighted;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4),
      child: Row(
        children: [
          Icon(Icons.check_circle_outline_rounded,
              size: 18,
              color: isHighlighted ? AppColors.primary : AppColors.secondary),
          const SizedBox(width: AppSpacing.sm),
          Text(feature.displayName,
              style: TextStyle(
                fontWeight: isHighlighted ? FontWeight.w600 : FontWeight.normal,
                color:
                    isHighlighted ? AppColors.onSurface : AppColors.secondary,
              )),
        ],
      ),
    );
  }
}

class _FeatureComparisonTable extends StatelessWidget {
  const _FeatureComparisonTable({required this.currentTier});
  final PlanTier currentTier;

  static const _rows = AppFeature.values;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text('Full Comparison',
            style: TextStyle(fontSize: 18, fontWeight: FontWeight.w700)),
        const SizedBox(height: AppSpacing.md),
        Table(
          columnWidths: const {
            0: FlexColumnWidth(3),
            1: FlexColumnWidth(1),
            2: FlexColumnWidth(1),
            3: FlexColumnWidth(1),
          },
          children: [
            TableRow(
              decoration: BoxDecoration(
                  color: AppColors.surfaceContainerLowest,
                  borderRadius: BorderRadius.circular(8)),
              children: const [
                _TableHeader('Feature'),
                _TableHeader('Free'),
                _TableHeader('Pro'),
                _TableHeader('Ent.'),
              ],
            ),
            for (final feature in _rows)
              TableRow(children: [
                Padding(
                  padding:
                      const EdgeInsets.symmetric(vertical: 10, horizontal: 8),
                  child: Text(feature.displayName,
                      style: const TextStyle(fontSize: 13)),
                ),
                _TableCell(PlanTier.free.includes(feature)),
                _TableCell(PlanTier.pro.includes(feature)),
                _TableCell(PlanTier.enterprise.includes(feature)),
              ]),
          ],
        ),
      ],
    );
  }
}

class _TableHeader extends StatelessWidget {
  const _TableHeader(this.text);
  final String text;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 8),
      child: Text(text,
          style: const TextStyle(fontWeight: FontWeight.w700, fontSize: 13),
          textAlign: TextAlign.center),
    );
  }
}

class _TableCell extends StatelessWidget {
  const _TableCell(this.included);
  final bool included;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 10),
      child: Icon(
        included ? Icons.check_rounded : Icons.remove,
        size: 18,
        color: included
            ? AppColors.primary
            : AppColors.secondary.withValues(alpha: 0.3),
      ),
    );
  }
}
