// =============================================================================
// FIREBASE CONFIGURATION — bookly-1f5f7
// Generated by flutterfire configure
// =============================================================================

import 'dart:io' show Platform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) {
      return android;
    } else if (Platform.isIOS) {
      return ios;
    } else {
      throw UnsupportedError('Unsupported platform');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: '1036884766294',
    projectId: 'bookly-1f5f7',
    authDomain: 'bookly-1f5f7.firebaseapp.com',
    storageBucket: 'bookly-1f5f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD1ozOEp976UbnNhdx6RrMtnCBerivdcM',
    appId: '1:1036884766294:android:853c6f5c3e706aae0595f7',
    messagingSenderId: '1036884766294',
    projectId: 'bookly-1f5f7',
    storageBucket: 'bookly-1f5f7.firebasestorage.app',
  );

  static const _iosApiKey =
      String.fromEnvironment('BOOKLY_IOS_FIREBASE_API_KEY');
  static const _iosAppId = String.fromEnvironment('BOOKLY_IOS_FIREBASE_APP_ID');
  static const _iosMessagingSenderId =
      String.fromEnvironment('BOOKLY_IOS_FIREBASE_MESSAGING_SENDER_ID');
  static const _iosProjectId =
      String.fromEnvironment('BOOKLY_IOS_FIREBASE_PROJECT_ID');
  static const _iosStorageBucket =
      String.fromEnvironment('BOOKLY_IOS_FIREBASE_STORAGE_BUCKET');
  static const _iosBundleId =
      String.fromEnvironment('BOOKLY_IOS_FIREBASE_BUNDLE_ID');

  /// iOS values are extracted from the real `GoogleService-Info.plist` by the
  /// hosted release workflow and supplied as compile-time definitions. Keeping
  /// one injected source avoids committing Firebase configuration files while
  /// ensuring secondary Firebase apps receive the same verified options.
  static FirebaseOptions get ios {
    const values = <String, String>{
      'API_KEY': _iosApiKey,
      'GOOGLE_APP_ID': _iosAppId,
      'GCM_SENDER_ID': _iosMessagingSenderId,
      'PROJECT_ID': _iosProjectId,
      'STORAGE_BUCKET': _iosStorageBucket,
      'BUNDLE_ID': _iosBundleId,
    };
    final missingKeys = values.entries
        .where((entry) => entry.value.isEmpty)
        .map((entry) => entry.key)
        .join(', ');
    if (missingKeys.isNotEmpty) {
      throw StateError(
        'iOS Firebase configuration is missing: $missingKeys. '
        'Build through the configured release workflow or provide the '
        'BOOKLY_IOS_FIREBASE_* dart-defines.',
      );
    }

    return const FirebaseOptions(
      apiKey: _iosApiKey,
      appId: _iosAppId,
      messagingSenderId: _iosMessagingSenderId,
      projectId: _iosProjectId,
      storageBucket: _iosStorageBucket,
      iosBundleId: _iosBundleId,
    );
  }
}
