// =============================================================================
// FIREBASE CONFIGURATION — bookly-1f5f7
// Generated by flutterfire configure
// =============================================================================

import 'dart:io' show Platform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) {
      return android;
    } else if (Platform.isIOS) {
      return ios;
    } else {
      throw UnsupportedError('Unsupported platform');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: '1036884766294',
    projectId: 'bookly-1f5f7',
    authDomain: 'bookly-1f5f7.firebaseapp.com',
    storageBucket: 'bookly-1f5f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD1ozOEp976UbnNhdx6RrMtnCBerivdcM',
    appId: '1:1036884766294:android:853c6f5c3e706aae0595f7',
    messagingSenderId: '1036884766294',
    projectId: 'bookly-1f5f7',
    storageBucket: 'bookly-1f5f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '1036884766294',
    projectId: 'bookly-1f5f7',
  );
}